dist: trusty

install:
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra dvipng

script:
    - make

after_success:
    - git checkout --orphan pdf
    - git rm -rf .
    - git add -f JAE-resume-2016.pdf JAE-CV-2016.pdf
    - git -c user.name='travis' -c user.email='travis' commit -m init
    - git push -f https://github.com/jellis18/cv pdf
#- git push -q -f https://dfm:$GITHUB_API_KEY@github.com/davidwhogg/mcmc pdf
